// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUOAveMiry3TxZsdG3IvU0PwBxazMM9x0',
    appId: '1:101013078019:web:9bf42a9e8a6c4576e30e36',
    messagingSenderId: '101013078019',
    projectId: 'fir-c23ac',
    authDomain: 'fir-c23ac.firebaseapp.com',
    storageBucket: 'fir-c23ac.appspot.com',
    measurementId: 'G-BVHST4Y2DX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJK00pyhnQ5Yo8YziNnDTV4sF5Po77LY0',
    appId: '1:101013078019:android:fed46fa0031c483be30e36',
    messagingSenderId: '101013078019',
    projectId: 'fir-c23ac',
    storageBucket: 'fir-c23ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBul5xMCSSGRVvx1r_Hj5mfRo0ZAeBrTdw',
    appId: '1:101013078019:ios:b7a91660c5e9cc93e30e36',
    messagingSenderId: '101013078019',
    projectId: 'fir-c23ac',
    storageBucket: 'fir-c23ac.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBul5xMCSSGRVvx1r_Hj5mfRo0ZAeBrTdw',
    appId: '1:101013078019:ios:b7a91660c5e9cc93e30e36',
    messagingSenderId: '101013078019',
    projectId: 'fir-c23ac',
    storageBucket: 'fir-c23ac.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUOAveMiry3TxZsdG3IvU0PwBxazMM9x0',
    appId: '1:101013078019:web:a251de24f7ea18b3e30e36',
    messagingSenderId: '101013078019',
    projectId: 'fir-c23ac',
    authDomain: 'fir-c23ac.firebaseapp.com',
    storageBucket: 'fir-c23ac.appspot.com',
    measurementId: 'G-6X4N43W1HD',
  );
}
